### ISSUE TITLE
(epub-test-fail: pkg-dir_rtl-root-ltr)

### ISSUE THREAD

**Issue by gautierchomel** [edrlab/thorium-reader-epub-tests#18]
The [pkg-dir_rtl-root-ltr](https://w3c.github.io/epub-tests/index.html#pkg-dir_rtl-root-ltr) test fails at 
![Screenshot of how it has to render with the ! first caracter on the left](https://user-images.githubusercontent.com/107039498/174793372-c646853e-636b-4198-9a67-b260959dc23e.png)

_It renders correctly in the window heading but not on catalog interface_

[OPF meta Title](https://github.com/w3c/epub-tests/blob/03d3b84722cb0f5c3439702c38e8b354f8f33e31/tests/pkg-dir_rtl-root-ltr/EPUB/package.opf#L14)
`<dc:title dir="rtl" xml:lang="he">CSS: הרפתקה חדשה!</dc:title>`

![Test table line 76](https://github.com/edrlab/thorium-reader-epub-tests/blob/main/Test_Thorium_2-0.md#76)

**Comment by danielweck** [comment]
This will be solved in two stages:
* fix in the "shared" parser (done): https://github.com/readium/r2-shared-js/commit/ec2a6cf845cb8c19bb73745cac0bc7fcdc934279
* fix in Thorium (in progress)

See how the RWPM `title` incorrectly assume `en` instead of `xml:lang` on the OPF package or local to `dc:title`:

https://streamer.edrlab.org/pub/aHR0cHM6Ly9naXRodWIuY29tL3czYy9lcHViLXRlc3RzL3Jhdy9tYWluL3Rlc3RzL3BrZy1kaXJfcnRsLXJvb3QtbHRyLmVwdWI%3D/manifest.json/show/all

**Comment by danielweck** [comment]
Update: the streamer deployment is now updated with the fixed r2-shared-js code, consequently the title and author JSON properties now carry the language info (from which we derive rtl direction):
https://streamer.edrlab.org/pub/aHR0cHM6Ly9naXRodWIuY29tL3czYy9lcHViLXRlc3RzL3Jhdy9tYWluL3Rlc3RzL3BrZy1kaXJfcnRsLXJvb3QtbHRyLmVwdWI%3D/manifest.json/show/all
(PS: I must investigate why the publisher property remains language-free)

**Comment by danielweck** [comment]
> (PS: I must investigate why the publisher property remains language-free)

Ok:
https://github.com/readium/r2-shared-js/blob/65506bc848b84eed235dee05f5f02c9077f64807/src/parser/epub/opf-author.ts#L15-L34

**Comment by danielweck** [comment]
Fixed.

Tested with `pkg-dir_rtl-root-ltr.epub` from https://github.com/w3c/epub-tests/blob/main/tests/pkg-dir_rtl-root-ltr.epub

<img width="1552" alt="Screenshot 2022-09-29 at 15 21 35" src="https://user-images.githubusercontent.com/625201/193058226-8098d3e8-91d5-45e9-b280-770ae6fdb358.png">
<img width="1552" alt="Screenshot 2022-09-29 at 15 22 15" src="https://user-images.githubusercontent.com/625201/193058243-1b612754-e408-47d1-928b-3737c303001a.png">
<img width="1552" alt="Screenshot 2022-09-29 at 15 22 52" src="https://user-images.githubusercontent.com/625201/193058249-2628f196-c754-4d46-a7e7-63b3f282a7a4.png">
<img width="1552" alt="Screenshot 2022-09-29 at 15 23 19" src="https://user-images.githubusercontent.com/625201/193058253-79ed5647-8923-45bc-849b-81dd7beda046.png">

**Comment by danielweck** [comment]
Fixed via https://github.com/edrlab/thorium-reader/commit/d67cab6ae21ddc2f9eecf27c8e0bdf1b26fa9a62

**Comment by danielweck** [comment]
Here is a more interesting test case:

https://github.com/IDPF/epub3-samples/tree/main/30/regime-anticancer-arabic/EPUB

=>

https://streamer.edrlab.org/pub/aHR0cHM6Ly9naXRodWIuY29tL0lEUEYvZXB1YjMtc2FtcGxlcy9yZWxlYXNlcy9kb3dubG9hZC8yMDE3MDYwNi9yZWdpbWUtYW50aWNhbmNlci1hcmFiaWMuZXB1Yg%3D%3D/manifest.json/show/all

```json
   "metadata": {

        "title": {
            "ar": "السرطان من  للوقاية الصحيح الغذائي  النظام",
            "fr": "Le Vrai Régime anti-cancer"
        },

        "author": [
            {
                "name": {
                    "ar": "دافيد  خيّاط لبروفيسورا",
                    "fr": "Pr David Khayat"
                }
            },
            {
                "name": {
                    "ar": "اردو هاتر ناتالي",
                    "fr": "Nathalie Hutter-Lardeau"
                }
            }
        ],
        "translator": {
            "name": {
                "ar": "فيّاض خليل مارينا",
                "fr": "Marina Khalil Fayad"
            }
        },
        "contributor": {
            "name": {
                "fr": "Vincent Gros"
            },
            "sortAs": "Gros, Vincent",
            "role": "mrk"
        },

        "language": "ar",

        "readingProgression": "rtl",

        "alternate-script": "فيّاض خليل مارينا",

    },
```

**Comment by danielweck** [comment]
Here we can see that when the Thorium UI is set to `fr` (French) the available `title` metadata is selected for display, whereas the default `en` (English) UI locale selects the first available `title` language which is `ar` (Arabic)

<img width="1552" alt="Screenshot 2022-09-29 at 15 50 44" src="https://user-images.githubusercontent.com/625201/193064840-0f122124-c260-42cf-b685-cd4357dbb004.png">
<img width="1552" alt="Screenshot 2022-09-29 at 15 49 39" src="https://user-images.githubusercontent.com/625201/193064823-6f6a854a-ff33-4fe1-aec6-90a64782452a.png">

**Comment by danielweck** [comment]
Note that publication "authors" are not subject to the same `title` logic ... yet. We will need to fix this, and several other instances too (e.g. `dc:description`)

**Comment by panaC** [comment]
fixed by https://github.com/edrlab/thorium-reader/commit/d67cab6ae21ddc2f9eecf27c8e0bdf1b26fa9a62
